"""creating a unique token table to the app

Revision ID: 68533d8e9b11
Revises: 
Create Date: 2025-01-20 20:59:11.039927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68533d8e9b11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posto_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posto_tokens')
    # ### end Alembic commands ###
