"""minha primeira migracao

Revision ID: 8443604a0aa8
Revises: 
Create Date: 2025-01-19 20:56:20.725926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8443604a0aa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=mysql.DECIMAL(precision=8, scale=3),
               type_=sa.DECIMAL(precision=7, scale=3),
               nullable=False)
        batch_op.alter_column('cidade',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('posto',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('preco',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=3, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.alter_column('cidade',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('entrega_combustivel', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=3, scale=2),
               nullable=False)

    with op.batch_alter_table('ponto_virada', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=3, scale=2),
               nullable=False)

    with op.batch_alter_table('posto_users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posto_users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=140),
               nullable=False)

    with op.batch_alter_table('ponto_virada', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=True)

    with op.batch_alter_table('entrega_combustivel', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=True)

    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.alter_column('cidade',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('abastecimentos', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('posto',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('cidade',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('volume',
               existing_type=sa.DECIMAL(precision=7, scale=3),
               type_=mysql.DECIMAL(precision=8, scale=3),
               nullable=True)

    op.drop_table('request_tokens')
    # ### end Alembic commands ###
